rm /usr/local/share/far2l/FarBel.lng
rm /usr/local/share/far2l/FarCze.lng
rm /usr/local/share/far2l/FarGer.lng
rm /usr/local/share/far2l/FarHun.hlf
rm /usr/local/share/far2l/FarHun.lng
rm /usr/local/share/far2l/FarPol.lng
rm /usr/local/share/far2l/FarRus.hlf
rm /usr/local/share/far2l/FarRus.lng
rm /usr/local/share/far2l/FarSpa.lng
rm /usr/local/share/far2l/FarUkr.hlf
rm /usr/local/share/far2l/FarUkr.lng
rm /usr/local/share/far2l/Plugins/align/plug/AlignBel.lng
rm /usr/local/share/far2l/Plugins/align/plug/AlignBel.lng
rm /usr/local/share/far2l/Plugins/align/plug/AlignRus.lng
rm /usr/local/share/far2l/Plugins/autowrap/plug/WrapBel.lng
rm /usr/local/share/far2l/Plugins/autowrap/plug/WrapRus.lng
rm /usr/local/share/far2l/Plugins/calc/plug/calcb.lng
rm /usr/local/share/far2l/Plugins/calc/plug/calcr.hlf
rm /usr/local/share/far2l/Plugins/calc/plug/calcr.lng
rm /usr/local/share/far2l/Plugins/colorer/plug/colorerb.lng
rm /usr/local/share/far2l/Plugins/colorer/plug/colorerr.hlf
rm /usr/local/share/far2l/Plugins/colorer/plug/colorerr.lng
rm /usr/local/share/far2l/Plugins/compare/plug/CmpRus.hlf
rm /usr/local/share/far2l/Plugins/compare/plug/CompBel.lng
rm /usr/local/share/far2l/Plugins/compare/plug/CompRus.lng
rm /usr/local/share/far2l/Plugins/drawline/plug/DrawBel.lng
rm /usr/local/share/far2l/Plugins/drawline/plug/DrawRus.hlf
rm /usr/local/share/far2l/Plugins/drawline/plug/DrawRus.lng
rm /usr/local/share/far2l/Plugins/editcase/plug/ECaseBel.lng
rm /usr/local/share/far2l/Plugins/editcase/plug/ECaseRus.hlf
rm /usr/local/share/far2l/Plugins/editcase/plug/ECaseRus.lng
rm /usr/local/share/far2l/Plugins/editorcomp/plug/editorcomp_be.lng
rm /usr/local/share/far2l/Plugins/editorcomp/plug/editorcomp_ru.lng
rm /usr/local/share/far2l/Plugins/filecase/plug/CaseBel.lng
rm /usr/local/share/far2l/Plugins/filecase/plug/CaseRus.hlf
rm /usr/local/share/far2l/Plugins/filecase/plug/CaseRus.lng
rm /usr/local/share/far2l/Plugins/incsrch/plug/incsrchr.hlf
rm /usr/local/share/far2l/Plugins/incsrch/plug/isrcrus.lng
rm /usr/local/share/far2l/Plugins/inside/plug/bel.lng
rm /usr/local/share/far2l/Plugins/inside/plug/rus.lng
rm /usr/local/share/far2l/Plugins/multiarc/plug/arcbel.lng
rm /usr/local/share/far2l/Plugins/multiarc/plug/arcrus.hlf
rm /usr/local/share/far2l/Plugins/multiarc/plug/arcrus.lng
rm /usr/local/share/far2l/Plugins/NetRocks/plug/bel.lng
rm /usr/local/share/far2l/Plugins/NetRocks/plug/rus.lng
rm /usr/local/share/far2l/Plugins/tmppanel/plug/TmpBel.lng
rm /usr/local/share/far2l/Plugins/tmppanel/plug/TmpRus.hlf
rm /usr/local/share/far2l/Plugins/tmppanel/plug/TmpRus.lng
rm /usr/local/share/far2l/Plugins/netcfg/plug/NetcfgBel.lng
rm /usr/local/share/far2l/Plugins/netcfg/plug/NetcfgRus.hlf
rm /usr/local/share/far2l/Plugins/netcfg/plug/NetcfgRus.lng
rm /usr/local/share/far2l/Plugins/processes/plug/ProcBel.lng
rm /usr/local/share/far2l/Plugins/processes/plug/ProcRus.hlf
rm /usr/local/share/far2l/Plugins/processes/plug/ProcRus.lng
rm /usr/local/share/far2l/Plugins/sqlplugin/plug/SqlBel.lng
rm /usr/local/share/far2l/Plugins/sqlplugin/plug/SqlRus.hlf
rm /usr/local/share/far2l/Plugins/sqlplugin/plug/SqlRus.lng
